# Generated by Django 5.0.3 on 2024-03-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_students_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=100)),
                ('employee_address', models.CharField(max_length=200)),
                ('employee_phone_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
